### ISSUE TITLE
additional data needed for Internal Error: 8

### ISSUE THREAD

**Issue by Fadavvi** [VirusTotal/yara-python#156]
Hi,
I try to find data about **Internal Error: 8**, but I found it's in default section of your switch/case:
https://github.com/VirusTotal/yara-python/blob/fa3795f9a8351c74b8dba05d05955e6b8d85d1f8/yara-python.c#L971

Anyone can help me to understand what happens in my codes? 
It's happened while I try to load (compiled) rules from a directory.

**Comment by plusvic** [comment]
The error comes from libyara, [error 8](https://github.com/VirusTotal/yara/blob/master/libyara/include/yara/error.h#L53) corresponds to `ERROR_UNSUPPORTED_FILE_VERSION `. Which version of `yara-python` are you using? In the latest version `ERROR_UNSUPPORTED_FILE_VERSION` is explicitly handled and returns its own error message instead of the generic: "Internal Error".

**Comment by Fadavvi** [comment]
Thanks @plusvic. 
Problem resolved by `pip3 install python-yara==4.0.2`.
 I used `pip3 install yara` before.
