### ISSUE TITLE
 It is impossible to scan directories whose names are in Russian, and it is also impossible to scan files in Russian

### ISSUE THREAD

**Issue by PheonixCS** [VirusTotal/yara-python#245]
![image](https://github.com/VirusTotal/yara-python/assets/91153526/9136d836-e4f5-482e-a4bd-4ddb87d8c90b)
![image](https://github.com/VirusTotal/yara-python/assets/91153526/fcd4e91b-67cb-48e4-8363-5ea637261613)

**Comment by plusvic** [comment]
This is a well known issue that won't be solved anytime soon. But there's an alternative, instead of passing `filepath` to `rules.match` read the file from Python and pass `data` to `rules.match`. This way Python handles the file reading, which should handle unicode path correctly. The problem with passing the file path directly to YARA is that YARA's API doesn't offer unicode support.
