### ISSUE TITLE
Seg fault with large rulesets

### ISSUE THREAD

**Issue by mlaferrera** [VirusTotal/yara-python#6]
I'm running into a similar issue as #3, but it occurs when I am matching against compiled rules from a file object:

```
>>> import yara
>>> # rules.yar is a 3.1Mb file with approximately 12k rules
>>> with open("rules.yar") as rules:
...       rules = yara.compile(file=rules)
>>> r.match(data="BADNESS")
[1] segmentation fault (core dumped)  python
```

**Comment by plutec** [comment]
Could be related wth #3 because I load too from a compiled rules file.

**Comment by wxsBSD** [comment]
I reached out to @mlaferrera earlier this week and got the ruleset which triggers the failure.

I tracked the internal errors down to really ugly regular expressions which are no longer valid because of commit a76bfc0 in the YARA repository. In particular, the if condition (https://github.com/plusvic/yara/blob/master/libyara/re.c#L666) is true for these two regular expressions which causes the compiler to error out. I'm not sure if bumping RE_MAX_SPLIT_ID is the right thing to do in the long run (the RE code in YARA is completely foreign to me).

I can provide the offending regular expression privately if necessary. Or, alternatively, if you are on the yaraexchange mailing list you can read my post on there about the offending rule.

**Comment by dspruell** [comment]
Wanted to remark on this too, I have several attempted regular expressions in our rule set that don't seem to respond well to the restrictions in place in 3.5.0. Subtle changes to introduce whitespace allowance in patterns with `\s*` result in the RE_MAX_SPLIT_ID related conditions being hit. 

For example, this regex works fine:

`/^document\.write\({1,2}\x27<div\s+(id=\x22\d+\x22 )?style=\x22((width: \d+px;|height: \d+px;|position: absolute;|left:-\d+px;|top: -\d+px;) ){4}(width: \d+px;|height: \d+px;|position: absolute;|left:-\d+px;|top: -\d+px;)\x22>\s*<iframe ((src=\x22[^\x22]+\x22|width=\d+|height=\d+) ){2}(src=\x22[^\x22]+\x22|width=\d+|height=\d+)\s*>\s*/`

...but this one causes "_/Users/dspruell/devel/yararules/rules/main.yar(601): error: internal fatal error_":

`/^document\.write\({1,2}\x27<div\s+(id=\x22\d+\x22 )?style=\x22((width: \d+px;|height: \d+px;|position: absolute;|left:\s*(0|-\d+)px;|top: -\d+px;) ){4}(width: \d+px;|height: \d+px;|position: absolute;|left:-\d+px;|top: -\d+px;)\x22>\s*<iframe ((src=\x22[^\x22]+\x22|width=\d+|height=\d+) ){2}(src=\x22[^\x22]+\x22|width=\d+|height=\d+)\s*>\s*/`

The problem is that some of the regexes that cause this issue are using pattern constructs that are required to meet match needs, and the expressions themselves aren't crazy like some examples that have been shared in various communities.

**Comment by plusvic** [comment]
I'm working on a fix to the internal errors caused by regexps reaching RE_MAX_SPLIT_ID. However the initial issue was related to segfault. Do we know the cause for the segfault?

**Comment by phantom0301** [comment]
Hi, I think this is because you installed yara and python-yara at the same time.  You should uninstalled the yara and the problem seems to be able to resolve
